### PR TITLE
WIP: Add More Functionality to the Auto Hanger Admin Command

### PR DESCRIPTION
**Pull request by spacebuilder2020**
Example: /hm autohanger [hangerNow (true/false)] [hangerStatic (true/false)] [hangerLarge (true/false)] [hangerSmall (true/false)]

The goal of this PR is to allow Admins to Auto-Hanger all grids for special events such as a world reset / cluster rebuild.  This should hopefully reduce the overhead Admins face when doing a world cluster rebuild while in addition allowing them to safely preserve player grids and thus prevent upset players loosing their stuff if the world has to reset unexpectedly. 

I am leaving this as WIP for now so that the command changes can be refined as needed.  I have tested this and it works in a local torch instance.

### CODE REVIEW

**Comment by spacebuilder2020** [comment]
@Casimir255 I see you added a saveAll functionality some time after this PR was summited.  I am not sure if this PR is still needed.  Having the ability to override what grids get hangered would still be useful.  What would be your recommendation for implementing that feature?  Should it be an option of the saveAll Command instead?

**Comment by Casimir255** [comment]
Apparently I didn't see this PR sorry!

Instead of adding on to the existing command with optional parameters, create new ones such as:
"!autohangar staticgrids"
"!autohangar largegrids"
"!autohangar smallgrids"

This makes it easier and doesn't break any existing command uses.

The autohangar main method optional parameters should be fine. If you want to fix the merge conflicts and remove my save all bool with just true on all three I'll merge it tomorrow.

**Comment by spacebuilder2020** [comment]
Yea, sorry, I have been busy with RL and haven't been able to make the updates.  I will try to get it fixed this weekend.

**Comment by spacebuilder2020** [comment]
Sorry for the long delays.  Here is the updated code.

**Pull request merged**
